### PR TITLE
Change auto deployment to use GitHub actions

### PR DESCRIPTION
**Pull request by SimonFrings**
Refs https://github.com/reactphp/website/pull/53 and https://github.com/clue/framework-x-website/pull/7.
Builds on top of #125 and #126

### CODE REVIEW

**Review by clue — COMMENTED** [review]
@SimonFrings Changes LGTM, does it make sense to add a badge to show last deployment date for this branch? 👍

**Comment by SimonFrings** [comment]
@clue, I think you're right, I'll add this to my PR :+1:

**Review by clue — APPROVED** [review]
@SimonFrings Thanks for the update, changes LGTM! :shipit:

**Comment by SimonFrings** [comment]
Also added a CI badge :D

**Review by clue — CHANGES_REQUESTED** [review]
Badge URL looks outdated, no?

**Review by clue — CHANGES_REQUESTED** [review]
Please review the badge URL and use the current format.

**Comment by SimonFrings** [comment]
@clue This should be the right one

**Pull request merged**
